services:
  midigen:
  
    container_name: fyp-midigen-container
    image: fyp-midigen-image
    build:
      context: ./midigen
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    volumes:
      - ./midigen:/app
    environment:
      HOST: 0.0.0.0
      PROT: 8020
    command: ["python", "main.py"]

  piano_transcription:
    container_name: fyp-piano-transcription-container
    image: fyp-piano-transcription-image
    build:
      context: ./piano_transcription
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./piano_transcription:/app
    environment:
      HOST: 0.0.0.0
      PROT: 8010
    command: ["python", "main.py"]